//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Envios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Envios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlEnvios.Resources.Envios", typeof(Envios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articulo.
        /// </summary>
        public static string ArticuloEnvio {
            get {
                return ResourceManager.GetString("ArticuloEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver Atras.
        /// </summary>
        public static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bascula Grande.
        /// </summary>
        public static string BasculaG {
            get {
                return ResourceManager.GetString("BasculaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bascula Pequeña.
        /// </summary>
        public static string BasculaP {
            get {
                return ResourceManager.GetString("BasculaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cod. Prove.
        /// </summary>
        public static string CodProvEnvio {
            get {
                return ResourceManager.GetString("CodProvEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Envio.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Envio.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilos Com.
        /// </summary>
        public static string EnvCom {
            get {
                return ResourceManager.GetString("EnvCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envio creado correctamente.
        /// </summary>
        public static string EnvInsertado {
            get {
                return ResourceManager.GetString("EnvInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el envio.
        /// </summary>
        public static string ErrInsertado {
            get {
                return ResourceManager.GetString("ErrInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Env.
        /// </summary>
        public static string FechaEnvio {
            get {
                return ResourceManager.GetString("FechaEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Env.
        /// </summary>
        public static string HoraEnvio {
            get {
                return ResourceManager.GetString("HoraEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Salida.
        /// </summary>
        public static string HoraSal {
            get {
                return ResourceManager.GetString("HoraSal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilos Env.
        /// </summary>
        public static string KilosEnvio {
            get {
                return ResourceManager.GetString("KilosEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula.
        /// </summary>
        public static string MatriculaEnvio {
            get {
                return ResourceManager.GetString("MatriculaEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo invalido.
        /// </summary>
        public static string ModelInsetado {
            get {
                return ResourceManager.GetString("ModelInsetado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Net.
        /// </summary>
        public static string PesadaNeto {
            get {
                return ResourceManager.GetString("PesadaNeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envios de Mercancia.
        /// </summary>
        public static string TituloEnvioMercancia {
            get {
                return ResourceManager.GetString("TituloEnvioMercancia", resourceCulture);
            }
        }
    }
}
