//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        public int ID_ARTICULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CODARTICULO { get; set; }
        public Nullable<bool> ACTIVAWEB { get; set; }
    }
}
