//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPOPROVEEDOR
    {
        public int IDCUPOPROV { get; set; }
        public string CODPROVEE { get; set; }
        public string CODARTICULO { get; set; }
        public Nullable<System.DateTime> FECHAINICIOCUPO { get; set; }
        public Nullable<System.DateTime> FEHAFINALCUPO { get; set; }
        public Nullable<decimal> PORCENTAGEASIG { get; set; }
        public bool ACTIVACUPO { get; set; }
    }
}
