//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIOMERCANCIA
    {
        public int IDENVIO { get; set; }
        public string CODPROVEEDOR { get; set; }
        public System.DateTime FECHAENVIO { get; set; }
        public Nullable<System.DateTime> HORAENVIO { get; set; }
        public string CODARTICULO { get; set; }
        public decimal KILOSENVIADOS { get; set; }
        public int ESTADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string MATRICULA { get; set; }
        public bool SENDEMAIL { get; set; }
        public int TIENENETO { get; set; }
    }
}
