//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BasculaEntities : DbContext
    {
        public BasculaEntities()
            : base("name=BasculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<ENVIOMERCANCIA> ENVIOMERCANCIA { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<ESTADOMERCANCIA> ESTADOMERCANCIA { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<PESADABASCULA> PESADABASCULA { get; set; }
        public virtual DbSet<CUPOKG> CUPOKG { get; set; }
        public virtual DbSet<CUPOPROVEEDOR> CUPOPROVEEDOR { get; set; }
    
        public virtual ObjectResult<PROC_ENVIOPESADA_Result> PROC_ENVIOPESADA(Nullable<System.DateTime> fechaHoy, string proveedor)
        {
            var fechaHoyParameter = fechaHoy.HasValue ?
                new ObjectParameter("fechaHoy", fechaHoy) :
                new ObjectParameter("fechaHoy", typeof(System.DateTime));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("Proveedor", proveedor) :
                new ObjectParameter("Proveedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_ENVIOPESADA_Result>("PROC_ENVIOPESADA", fechaHoyParameter, proveedorParameter);
        }
    
        public virtual ObjectResult<LISTAENVIOSFECHAPROVEEDOR_Result> LISTAENVIOSFECHAPROVEEDOR(Nullable<System.DateTime> fechaEnvio, Nullable<System.DateTime> fechaFin, string codproveedor)
        {
            var fechaEnvioParameter = fechaEnvio.HasValue ?
                new ObjectParameter("fechaEnvio", fechaEnvio) :
                new ObjectParameter("fechaEnvio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codproveedorParameter = codproveedor != null ?
                new ObjectParameter("codproveedor", codproveedor) :
                new ObjectParameter("codproveedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTAENVIOSFECHAPROVEEDOR_Result>("LISTAENVIOSFECHAPROVEEDOR", fechaEnvioParameter, fechaFinParameter, codproveedorParameter);
        }
    
        public virtual ObjectResult<ALLCUPOSPROVEEDOR_Result> ALLCUPOSPROVEEDOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ALLCUPOSPROVEEDOR_Result>("ALLCUPOSPROVEEDOR");
        }
    
        public virtual ObjectResult<Nullable<decimal>> KILOS_SEMANA_PROVEEDOR(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string codproveedor)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codproveedorParameter = codproveedor != null ?
                new ObjectParameter("codproveedor", codproveedor) :
                new ObjectParameter("codproveedor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("KILOS_SEMANA_PROVEEDOR", fechaInicioParameter, fechaFinParameter, codproveedorParameter);
        }
    
        public virtual int CANCELAENVIO(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CANCELAENVIO", idParameter);
        }
    
        public virtual ObjectResult<LISTAENVIOSIDPROVEEDOR_Result> LISTAENVIOSIDPROVEEDOR(Nullable<int> idEnvio)
        {
            var idEnvioParameter = idEnvio.HasValue ?
                new ObjectParameter("idEnvio", idEnvio) :
                new ObjectParameter("idEnvio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTAENVIOSIDPROVEEDOR_Result>("LISTAENVIOSIDPROVEEDOR", idEnvioParameter);
        }
    
        public virtual ObjectResult<CANCELAENVIOEMAIL_Result> CANCELAENVIOEMAIL(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CANCELAENVIOEMAIL_Result>("CANCELAENVIOEMAIL", idParameter);
        }
    
        public virtual ObjectResult<RECUPERAENVIOSPROVEE_Result> RECUPERAENVIOSPROVEE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RECUPERAENVIOSPROVEE_Result>("RECUPERAENVIOSPROVEE");
        }
    
        public virtual ObjectResult<RECUPERAENVIOSPROVEE1_Result> RECUPERAENVIOSPROVEE1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RECUPERAENVIOSPROVEE1_Result>("RECUPERAENVIOSPROVEE1");
        }
    
        public virtual ObjectResult<TODOSLOSENVIOSPROVEE_Result> TODOSLOSENVIOSPROVEE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TODOSLOSENVIOSPROVEE_Result>("TODOSLOSENVIOSPROVEE");
        }
    }
}
