//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESADABASCULA
    {
        public int ID_PESADA { get; set; }
        public string ID_TICKET { get; set; }
        public string MATRICULA { get; set; }
        public string REMOLQUE { get; set; }
        public string COD_PROV { get; set; }
        public string COD_CLIE { get; set; }
        public Nullable<int> COD_ART { get; set; }
        public Nullable<decimal> PRECIOKG { get; set; }
        public Nullable<System.DateTime> FECHAENTRADA { get; set; }
        public Nullable<System.DateTime> HORAENTRADA { get; set; }
        public Nullable<System.DateTime> FECHASALIDA { get; set; }
        public Nullable<System.DateTime> HORASALIDA { get; set; }
        public Nullable<decimal> PESADA1 { get; set; }
        public Nullable<decimal> PESADA2 { get; set; }
        public Nullable<decimal> PESADANETO { get; set; }
        public Nullable<int> PRIMEPESADA { get; set; }
        public Nullable<int> SECUNPESADA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string USERPESADA { get; set; }
        public string INFOMODPESADA { get; set; }
        public Nullable<int> ESTADOCAMION { get; set; }
        public Nullable<int> ESTADOMERCANCIA { get; set; }
        public Nullable<bool> BALSAGRANDE { get; set; }
        public Nullable<bool> BALSAPEQUENA { get; set; }
        public Nullable<int> IDENVIOWEB { get; set; }
        public Nullable<bool> EMAILENVIADO { get; set; }
        public Nullable<decimal> VGMTARA { get; set; }
    }
}
