//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public string CODPROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string CIF { get; set; }
        public string DIRECCION { get; set; }
        public string POBLACION { get; set; }
        public string PROVINCIA { get; set; }
        public string CODPOSTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
    }
}
